[package]
name = "selfportrait"
version = "0.1.0"
authors = ["Axel Cocat <ax.cocat@gmail.com>"]
edition = "2018"

[dependencies]
serenity = { git = "https://github.com/r-o-b-o-t-o/serenity", branch = "current" }
typemap = "0.3.3"
toml = "0.5.5"
serde = "1.0.102"
serde_derive = "1.0.102"
ctrlc = "3.1.3"
log = { version = "0.4.8", features = ["serde"] }
fern = "0.5.9"
chrono = "0.4.9"
unicode-segmentation = "1.5.0"
strfmt = "0.1.6"
actix-web = "1.0.8"
actix-files = "0.1.6"
