[logging]
file = "selfportrait.log"
level = "Info"

[www]
enabled = true
bind_host = "127.0.0.1"
bind_port = 41653
base_url = "http://selfportrait.mywebsite.com:{port}"
workers = 4

[[users]]
active = true
discord_id = 123456789
token = "<token>"
command_prefix = "s."
emote_prefix = ">"
text_emote_prefix = "$"

[[users]]
active = false
discord_id = 987654321
token = "<token>"
command_prefix = "/sp "
emote_prefix = "?"
text_emote_prefix = ":"
