fetch_twitch_emotes_infos = true
twitch_app_client_id = "<client id>"

[logging]
file = "selfportrait.log"
level = "Info"

[www]
enabled = true
bind_host = "127.0.0.1"
bind_port = 41653
base_url = "http://selfportrait.mywebsite.com:{port}"
workers = 4

[default_user]
active = true
command_prefix = "s."
emote_prefix = ">"
twitch_emote_prefix = "%"
text_emote_prefix = "$"

[[users]] # first user
discord_id = 123456789
token = "<token>"

[[users]] # second user
active = false
discord_id = 987654321
token = "<token>"
command_prefix = "/sp " # you can override every value with a custom one per user
emote_prefix = "?"
twitch_emote_prefix = "ยง"
text_emote_prefix = ":"
