[logging]
file = "selfportrait.log"
level = "INFO"

[www]
enabled = true
bind_host = "127.0.0.1"
bind_port = 41653
base_url = "http://selfportrait.mywebsite.com:{port}"
workers = 4
twitch_emotes_manager_host = "roboto.space"
twitch_emotes_manager_port = 41654

[default_user]
active = true
command_prefix = "s."
emote_prefix = ">"
twitch_emote_prefix = "%"
text_emote_prefix = "$"

[users.my_first_user]
discord_id = 123456789
token = "<token>"

[users.another_user]
active = false
discord_id = 987654321
token = "<token>"
command_prefix = "/sp " # you can override every value with a custom one per user
emote_prefix = "?"
twitch_emote_prefix = "ยง"
text_emote_prefix = ":"
